export interface Candidate {
    id: number
    name: string
    role: string
    location: string
    experience: string
    matchScore: number
    status: 'shortlisted' | 'interview' | 'new' | 'pending' | 'matched' | null
    skills: Array<{ name: string; level: number }>
    github: { repos: number; stars: number; contributions: number }
    leetcode: { solved: number; contests: number; ranking: string }
  }
  
  export const candidates: Candidate[] = [
    {
      id: 1,
      name: "Alex Morgan",
      role: "Senior Frontend Developer",
      location: "San Francisco, CA",
      experience: "7 years",
      matchScore: 92,
      status: 'shortlisted',
      skills: [
        { name: "React", level: 95 },
        { name: "TypeScript", level: 90 },
        { name: "Next.js", level: 85 },
        { name: "TailwindCSS", level: 88 },
      ],
      github: { repos: 32, stars: 450, contributions: 1240 },
      leetcode: { solved: 320, contests: 15, ranking: "Top 5%" },
    },
    {
      id: 2,
      name: "Sarah Chen",
      role: "Full Stack Engineer",
      location: "New York, NY",
      experience: "5 years",
      matchScore: 88,
      status: 'interview',
      skills: [
        { name: "Node.js", level: 92 },
        { name: "React", level: 85 },
        { name: "MongoDB", level: 80 },
        { name: "GraphQL", level: 78 },
      ],
      github: { repos: 24, stars: 320, contributions: 980 },
      leetcode: { solved: 280, contests: 12, ranking: "Top 10%" },
    },
    {
      id: 3,
      name: "Michael Johnson",
      role: "Backend Developer",
      location: "Austin, TX",
      experience: "4 years",
      matchScore: 85,
      status: 'new',
      skills: [
        { name: "Python", level: 90 },
        { name: "Django", level: 85 },
        { name: "PostgreSQL", level: 82 },
        { name: "Docker", level: 75 },
      ],
      github: { repos: 18, stars: 210, contributions: 760 },
      leetcode: { solved: 240, contests: 8, ranking: "Top 15%" },
    },
    {
      id: 4,
      name: "Emily Rodriguez",
      role: "UI/UX Developer",
      location: "Seattle, WA",
      experience: "6 years",
      matchScore: 90,
      status: 'pending',
      skills: [
        { name: "Figma", level: 95 },
        { name: "React", level: 88 },
        { name: "CSS/SCSS", level: 92 },
        { name: "Animation", level: 90 },
      ],
      github: { repos: 22, stars: 380, contributions: 920 },
      leetcode: { solved: 180, contests: 5, ranking: "Top 25%" },
    },
    {
      id: 5,
      name: "David Kim",
      role: "DevOps Engineer",
      location: "Chicago, IL",
      experience: "8 years",
      matchScore: 87,
      status: 'matched',
      skills: [
        { name: "Kubernetes", level: 92 },
        { name: "AWS", level: 90 },
        { name: "Terraform", level: 85 },
        { name: "CI/CD", level: 88 },
      ],
      github: { repos: 28, stars: 290, contributions: 1050 },
      leetcode: { solved: 150, contests: 3, ranking: "Top 30%" },
    },
    {
      id: 6,
      name: "Olivia Wilson",
      role: "Mobile Developer",
      location: "Portland, OR",
      experience: "5 years",
      matchScore: 84,
      status: 'new',
      skills: [
        { name: "React Native", level: 90 },
        { name: "Swift", level: 85 },
        { name: "Kotlin", level: 82 },
        { name: "Firebase", level: 80 },
      ],
      github: { repos: 20, stars: 240, contributions: 820 },
      leetcode: { solved: 210, contests: 7, ranking: "Top 20%" },
    },
    {
      id: 7,
      name: "James Lee",
      role: "ML Engineer",
      location: "Boston, MA",
      experience: "6 years",
      matchScore: 89,
      status: 'shortlisted',
      skills: [
        { name: "Python", level: 95 },
        { name: "TensorFlow", level: 92 },
        { name: "PyTorch", level: 88 },
        { name: "SQL", level: 85 },
      ],
      github: { repos: 25, stars: 420, contributions: 1100 },
      leetcode: { solved: 290, contests: 10, ranking: "Top 8%" },
    },
    {
      id: 8,
      name: "Sofia Martinez",
      role: "Security Engineer",
      location: "Miami, FL",
      experience: "7 years",
      matchScore: 86,
      status: 'interview',
      skills: [
        { name: "Penetration Testing", level: 94 },
        { name: "Network Security", level: 92 },
        { name: "Python", level: 85 },
        { name: "Cloud Security", level: 88 },
      ],
      github: { repos: 30, stars: 380, contributions: 950 },
      leetcode: { solved: 200, contests: 6, ranking: "Top 18%" },
    },
    {
      id: 9,
      name: "Lucas Anderson",
      role: "Blockchain Developer",
      location: "Denver, CO",
      experience: "4 years",
      matchScore: 83,
      status: 'pending',
      skills: [
        { name: "Solidity", level: 90 },
        { name: "Web3.js", level: 88 },
        { name: "Smart Contracts", level: 85 },
        { name: "JavaScript", level: 82 },
      ],
      github: { repos: 22, stars: 280, contributions: 780 },
      leetcode: { solved: 170, contests: 4, ranking: "Top 28%" },
    },
    {
      id: 10,
      name: "Emma Thompson",
      role: "Data Engineer",
      location: "Toronto, CA",
      experience: "5 years",
      matchScore: 91,
      status: 'matched',
      skills: [
        { name: "Apache Spark", level: 93 },
        { name: "Python", level: 90 },
        { name: "SQL", level: 92 },
        { name: "Airflow", level: 85 },
      ],
      github: { repos: 28, stars: 410, contributions: 1150 },
      leetcode: { solved: 260, contests: 9, ranking: "Top 12%" },
    },
    {
      id: 11,
      name: "Ryan Patel",
      role: "Cloud Architect",
      location: "Vancouver, CA",
      experience: "9 years",
      matchScore: 94,
      status: 'shortlisted',
      skills: [
        { name: "AWS", level: 96 },
        { name: "Azure", level: 92 },
        { name: "Terraform", level: 90 },
        { name: "Docker", level: 88 },
      ],
      github: { repos: 35, stars: 520, contributions: 1400 },
      leetcode: { solved: 310, contests: 14, ranking: "Top 6%" },
    },
    {
      id: 12,
      name: "Isabella Kim",
      role: "AR/VR Developer",
      location: "Los Angeles, CA",
      experience: "4 years",
      matchScore: 85,
      status: 'new',
      skills: [
        { name: "Unity", level: 92 },
        { name: "C#", level: 88 },
        { name: "3D Modeling", level: 85 },
        { name: "AR Kit", level: 82 },
      ],
      github: { repos: 20, stars: 260, contributions: 720 },
      leetcode: { solved: 160, contests: 5, ranking: "Top 32%" },
    }
  ]